use Proyecto

Create procedure AGREGAR_USUARIO
@USUARIO_USUARIO varchar(50),
@CONTRASEÑA_USUARIO varchar(20),
@NOMBRE_USUARIO varchar(35),
@ROL_USUARIO varchar(35),
@ESTADO_USUARIO varchar(10)
AS
INSERT INTO USUARIO(Usuario_Usuario,Contraseña_Usuario,Nombre_Usuario,Rol_Usuario,Estado_Usuario)
VALUES (@USUARIO_USUARIO,@CONTRASEÑA_USUARIO,@NOMBRE_USUARIO,@ROL_USUARIO,@ESTADO_USUARIO)	

exec AGREGAR_USUARIO 'Admin1','12345','Cristian','Administrador del sistema','Activo'

Create procedure AGREGAR_CARGO
@CODIGO_CARGO varchar(10),
@NOMBRE_CARGO varchar(15),
@ESTADO_CARGO varchar(10)
AS
INSERT INTO CARGO(Codigo_Cargo,Nombre_Cargo,Estado_Cargo)
VALUES (@CODIGO_CARGO,@NOMBRE_CARGO,@ESTADO_CARGO)

select*from PROVEEDORES

Create procedure AGREGAR_COMPROBANTE
@RAZON_COMPROBANTE varchar(70),
@FECHA_COMPROBANTE datetime, 
@NOMBRE_COMPROBANTE varchar(40),
@ESTADO_COMPROBANTE varchar(10)
AS
INSERT INTO COMPROBANTE(Razon_Comprobante,Fecha_Comprobante,Nombre_Comprobante,Estado_Comprobante)
VALUES (@RAZON_COMPROBANTE,@FECHA_COMPROBANTE,@NOMBRE_COMPROBANTE,@ESTADO_COMPROBANTE)

Create procedure AGREGAR_FORMAS_PAGOS
@CODIGO_FORMAPG varchar(10),
@NOMBRE_FORMAPG varchar(20),
@ESTADO_FORMAPG varchar(10)
AS
INSERT INTO FORMAS_PAGOS(Codigo_FormaPG,Nombre_FormaPG,Estado_FormaPG)
VALUES (@CODIGO_FORMAPG,@NOMBRE_FORMAPG,@ESTADO_FORMAPG)

Create procedure AGREGAR_PROVEEDORES
@CODIGO_PROVEEDORES numeric,
@DIRECCION_PROVEEDORES varchar(45),
@TELEFONO_PROVEEDORES numeric,
@NOMBRE_PROVEEDORES varchar(35),
@RAZON_COMPROBANTE_PROVEEDORES_FK  varchar(70),
@ESTADO_PROVEEDORES varchar(10)
AS
INSERT INTO PROVEEDORES(Codigo_Proveedores,Direccion_Proveedores,Telefono_Proveedores,Nombre_Proveedores,Razon_Comprobante_Proveedores_FK,Estado_Proveedores)
VALUES (@CODIGO_PROVEEDORES,@DIRECCION_PROVEEDORES,@TELEFONO_PROVEEDORES,@NOMBRE_PROVEEDORES,@RAZON_COMPROBANTE_PROVEEDORES_FK,@ESTADO_PROVEEDORES)

Create procedure AGREGAR_EMPLEADO
@CODIGO_EMPLEADO NUMERIC,
@ID_EMPLEADO NUMERIC,
@NOMBRE_EMPLEADO VARCHAR(30),
@DIRECCION_EMPLEADO VARCHAR(25),
@TELEFONO_EMPLEADO NUMERIC,
@FECHANACI_EMPLEADO DATETIME,
@GENERO_EMPLEADO VARCHAR(10),
@SALARIO_EMPLEADO FLOAT,
@USUARIO_USUARIO_EMPLEADO_FK VARCHAR(50),
@CODIGO_CARGO_EMPLEADO_FK VARCHAR(10),
@ESTADO_EMPLEADO VARCHAR(10),
@CODIGO_PROVEEDORES_EMPLEADO_FK NUMERIC
AS
INSERT INTO EMPLEADO(Codigo_Empleado,Id_Empleado,Nombre_Empleado,Direccion_Empleado,Telefono_Empleado,FechaNaci_Empleado,Genero_Empleado,Salario_Empleado,Usuario_Usuario_Empleado_FK,Codigo_Cargo_Empleado_FK,Estado_Empleado,Codigo_Proveedores_Empleado_FK)
VALUES (@CODIGO_EMPLEADO,@ID_EMPLEADO,@NOMBRE_EMPLEADO,@DIRECCION_EMPLEADO,@TELEFONO_EMPLEADO,@FECHANACI_EMPLEADO,@GENERO_EMPLEADO,@SALARIO_EMPLEADO,@USUARIO_USUARIO_EMPLEADO_FK,@CODIGO_CARGO_EMPLEADO_FK,@ESTADO_EMPLEADO,@CODIGO_PROVEEDORES_EMPLEADO_FK)

Create procedure AGREGAR_FACTCOMPRA
@CODIGO_FACTCOMP numeric,
@CODIGO_EMPLEADO_FACTCOMP_FK numeric,
@CODIGO_PROVEEDORES_FACTCOMP_FK numeric,
@FECHA_FACTCOMP datetime,
@VALOR_FACTCOMP Float,
@ESTADO_FACTCOMP varchar(10)
AS
INSERT INTO FACTURA_COMPRA(Codigo_FactComp,Codigo_Empleado_FactComp_FK,Codigo_Proveedores_FactComp_FK,Fecha_FactComp,Valor_FactComp,Estado_FactComp)
VALUES (@CODIGO_FACTCOMP,@CODIGO_EMPLEADO_FACTCOMP_FK,@CODIGO_PROVEEDORES_FACTCOMP_FK,@FECHA_FACTCOMP,@VALOR_FACTCOMP,@ESTADO_FACTCOMP)


Create procedure AGREGAR_CLIENTE
@CODIGO_CLIENTE numeric,
@ID_CLIENTE numeric,
@NOMBRE_CLIENTE varchar(30),
@DIRECCION_CLIENTE varchar(25),
@TELEFONO_CLIENTE Numeric,
@GENERO_CLIENTE varchar(10),
@CODIGO_EMPLEADO_CLIENTE_FK numeric,
@ESTADO_CLIENTE varchar(10)
AS
INSERT INTO CLIENTE(Codigo_Cliente,Id_Cliente,Nombre_Cliente,Direccion_Cliente,Telefono_Cliente,Genero_Cliente,Codigo_Empleado_Cliente_FK,Estado_Cliente)
VALUES (@CODIGO_CLIENTE,@ID_CLIENTE,@NOMBRE_CLIENTE,@DIRECCION_CLIENTE,@TELEFONO_CLIENTE,@GENERO_CLIENTE,@CODIGO_EMPLEADO_CLIENTE_FK,@ESTADO_CLIENTE)
select*from CLIENTE

Create procedure AGREGAR_FACTVENTA
@CODIGO_FACTVENT numeric,
@CODIGO_EMPLEADO_FACTVENT_FK numeric,
@CODIGO_CLIENTE_FACTVENT_FK numeric,
@FECHA_FACTVENT datetime,
@VALOR_FACTVENT float,
@ESTADO_FACTVENT varchar(10)
AS
INSERT INTO FACTURA_VENTA(Codigo_FactVent,Codigo_Empleado_FactVent_FK,Codigo_Cliente_FactVent_FK,Fecha_FactVent,Valor_FactVent,Estado_FactVent)
VALUES (@CODIGO_FACTVENT,@CODIGO_EMPLEADO_FACTVENT_FK ,@CODIGO_CLIENTE_FACTVENT_FK ,@FECHA_FACTVENT,@VALOR_FACTVENT,@ESTADO_FACTVENT)

Create procedure AGREGAR_RECIBO_CAJA
@CODIGO_CLIENTE_RECICAJA_FK numeric,
@CODIGO_FACTVENT_RECICAJA_FK numeric,
@FECHA_RECICAJA datetime,
@VALOR_RECICAJA FLOAT,
@DESCRIPCION_RECICAJA VARCHAR(50),
@ESTADO_RECICAJA VARCHAR(10)
AS
INSERT INTO RECIBO_CAJA(Codigo_Cliente_ReciCaja_FK,Codigo_FactVent_ReciCaja_FK,Fecha_ReciCaja,Valor_ReciCaja,Descripcion_ReciCaja,Estado_ReciCaja)
VALUES (@CODIGO_CLIENTE_RECICAJA_FK,@CODIGO_FACTVENT_RECICAJA_FK,@FECHA_RECICAJA,@VALOR_RECICAJA,@DESCRIPCION_RECICAJA,@ESTADO_RECICAJA)

create procedure AGREGAR_PAGOS
@VALOR_PAGOS FLOAT,
@CODIGO_FORMAPG_PAGOS_FK VARCHAR(10),
@FECHA_PAGOS datetime,
@CODIGO_EMPLEADO_PAGOS_FK NUMERIC,
@CODIGO_CLIENTE_PAGOS_FK NUMERIC,
@CODIGO_FACTVENT_PAGOS_FK NUMERIC,
@CODIGO_FACTCOMP_PAGOS_FK NUMERIC,
@ESTADO_PAGOS varchar(10)
AS
INSERT INTO PAGOS(Valor_Pagos,Codigo_FormaPG_Pagos_FK,Fecha_Pagos,Codigo_Empleado_Pagos_FK,Codigo_Cliente_Pagos_FK,Codigo_FactVent_Pagos_FK,Codigo_FactComp_Pagos_FK,Estado_Pagos)
VALUES (@VALOR_PAGOS,@CODIGO_FORMAPG_PAGOS_FK,@FECHA_PAGOS,@CODIGO_EMPLEADO_PAGOS_FK,@CODIGO_CLIENTE_PAGOS_FK,@CODIGO_FACTVENT_PAGOS_FK,@CODIGO_FACTCOMP_PAGOS_FK,@ESTADO_PAGOS)


CREATE PROCEDURE VALIDAR_USUARIO 
@USUARIO varchar(50),
@CONTRASEÑA varchar(20),
@NOMBRE varchar(35),
@ROL varchar(35),
@ESTADO varchar(10)
AS
SELECT*FROM USUARIO
WHERE @USUARIO = Usuario_Usuario and @CONTRASEÑA = Contraseña_Usuario and @NOMBRE = Nombre_Usuario and @ROL = Rol_Usuario and @ESTADO =Estado_Usuario
GO

select*from USUARIO
select*from CARGO
select*from COMPROBANTE
select*from FORMAS_PAGOS
select*from PROVEEDORES
select*from EMPLEADO
select*from FACTURA_COMPRA
select*from CLIENTE
select*from FACTURA_VENTA
select*from RECIBO_CAJA
select*from PAGOS
