use Proyecto

CREATE PROCEDURE ELIMINAR_USUARIO
@USUARIOINISESION  varchar(50),
@ESTADOINISESION VARCHAR(10)
AS
IF @ESTADOINISESION='ACTIVO'
BEGIN 
UPDATE USUARIO
SET Estado_Usuario='ACTIVO'
where Usuario_Usuario=@USUARIOINISESION
end
if @ESTADOINISESION='INACTIVO'
update USUARIO
set Estado_Usuario='INACTIVO'
where Usuario_Usuario=@USUARIOINISESION
go

CREATE PROCEDURE ELIMINAR_CARGO
@CODIGOCARGO VARCHAR(10),
@ESTADOCARGO VARCHAR(10)
AS
IF @ESTADOCARGO='ACTIVO'
BEGIN 
UPDATE CARGO
SET Estado_Cargo='ACTIVO'
where Codigo_Cargo=@CODIGOCARGO
end
if @ESTADOCARGO='INACTIVO'
update CARGO
set Estado_Cargo='INACTIVO'
where Codigo_Cargo=@CODIGOCARGO
go

CREATE PROCEDURE ELIMINAR_COMPROBANTE
@RAZONCOMPROBANTE varchar(70),
@ESTADOCOMPROBANTE VARCHAR(10)
AS
IF @ESTADOCOMPROBANTE='ACTIVO'
BEGIN 
UPDATE COMPROBANTE
SET Estado_Comprobante='ACTIVO'
where Razon_Comprobante=@RAZONCOMPROBANTE
end
if @ESTADOCOMPROBANTE='INACTIVO'
update COMPROBANTE
set Estado_Comprobante='INACTIVO'
where Razon_Comprobante=@RAZONCOMPROBANTE
go

CREATE PROCEDURE ELIMINAR_FORMAPG
@CODIGOFORMAPG varchar(10),
@ESTADOFORMAPG VARCHAR(10)
AS
IF @ESTADOFORMAPG='ACTIVO'
BEGIN 
UPDATE FORMAS_PAGOS
SET Estado_FormaPG='ACTIVO'
where Codigo_FormaPG=@CODIGOFORMAPG
end
if @ESTADOFORMAPG='INACTIVO'
update FORMAS_PAGOS
set Estado_FormaPG='INACTIVO'
where Codigo_FormaPG=@CODIGOFORMAPG
go

CREATE PROCEDURE ELIMINAR_PROVEEDORES
@CODIGOPROVEEDORES NUMERIC,
@ESTADOPROVEEDORES VARCHAR(10)
AS
IF @ESTADOPROVEEDORES='ACTIVO'
BEGIN 
UPDATE PROVEEDORES
SET Estado_Proveedores='ACTIVO'
where Codigo_Proveedores=@CODIGOPROVEEDORES
end
if @ESTADOPROVEEDORES='INACTIVO'
update PROVEEDORES
set Estado_Proveedores='INACTIVO'
where Codigo_Proveedores=@CODIGOPROVEEDORES
go

CREATE PROCEDURE ELIMINAR_EMPLEADO
@CODIGOEMPLEADO NUMERIC,
@ESTADOEMPLEADO VARCHAR(10)
AS
IF @ESTADOEMPLEADO='ACTIVO'
BEGIN 
UPDATE EMPLEADO
SET Estado_Empleado='ACTIVO'
where Codigo_Empleado=@CODIGOEMPLEADO
end
if @ESTADOEMPLEADO='INACTIVO'
update EMPLEADO
set Estado_Empleado='INACTIVO'
where Codigo_Empleado=@CODIGOEMPLEADO
go

CREATE PROCEDURE ELIMINAR_FACTCOMPRA
@CODIGOFACCOMPRA NUMERIC,
@ESTADOFACTCOMPRA VARCHAR(10)
AS
IF @ESTADOFACTCOMPRA='ACTIVO'
BEGIN 
UPDATE FACTURA_COMPRA
SET Estado_FactComp='ACTIVO'
where Codigo_FactComp=@CODIGOFACCOMPRA
end
if @ESTADOFACTCOMPRA='INACTIVO'
update FACTURA_COMPRA
set Estado_FactComp='INACTIVO'
where Codigo_FactComp=@CODIGOFACCOMPRA
go

CREATE PROCEDURE ELIMINAR_CLIENTE
@CODIGOCLIENTE NUMERIC,
@ESTADOCLIENTE VARCHAR(10)
AS
IF @ESTADOCLIENTE='ACTIVO'
BEGIN 
UPDATE CLIENTE
SET Estado_cliente='ACTIVO'
where Codigo_Cliente=@CODIGOCLIENTE
end
if @ESTADOCLIENTE='INACTIVO'
update CLIENTE
set Estado_Cliente='INACTIVO'
where Codigo_Cliente=@CODIGOCLIENTE
go

CREATE PROCEDURE ELIMINAR_FACTURA_VENTA
@CODIGOFACVENTA NUMERIC,
@ESTADOFACVENTA VARCHAR(10)
AS
IF @ESTADOFACVENTA='ACTIVO'
BEGIN 
UPDATE FACTURA_VENTA
SET Estado_FactVent='ACTIVO'
where Codigo_FactVent=@CODIGOFACVENTA
end
if @ESTADOFACVENTA='INACTIVO'
update FACTURA_VENTA
set Estado_FactVent='INACTIVO'
where Codigo_FactVent=@CODIGOFACVENTA
go

CREATE PROCEDURE ELIMINAR_RECIBO_CAJA
@CODIGORECIBOCAJA NUMERIC,
@ESTADORECICAJA VARCHAR(10)
AS
IF @ESTADORECICAJA='ACTIVO'
BEGIN 
UPDATE RECIBO_CAJA
SET Estado_ReciCaja='ACTIVO'
where Codigo_ReciCaja=@CODIGORECIBOCAJA
end
if @ESTADORECICAJA='INACTIVO'
update RECIBO_CAJA
set Estado_ReciCaja='INACTIVO'
where Codigo_ReciCaja=@ESTADORECICAJA
go

CREATE PROCEDURE ELIMINAR_PAGOS
@NUMEROPAGOS NUMERIC,
@ESTADOPAGOS VARCHAR(10)
AS
IF @ESTADOPAGOS='ACTIVO'
BEGIN 
UPDATE PAGOS
SET Estado_Pagos ='ACTIVO'
where Numero_pagos=@NUMEROPAGOS
end
if @ESTADOPAGOS='INACTIVO'
update PAGOS
set Estado_Pagos='INACTIVO'
where Numero_pagos=@NUMEROPAGOS
go