use Proyecto

CREATE PROCEDURE MODIFICAR_INI_SESION
@MOUSUARIOSESION varchar(50),
@MOCONTRASEÑASESION varchar(20),
@MONOMBRESESION varchar(35),
@MOROLSESION varchar(35),
@MOESTADOSESION varchar(10)
AS
UPDATE INICIO_SESION
SET Contraseña_Usuario = @MOCONTRASEÑASESION, Nombre_Usuario = @MONOMBRESESION,Rol_Usuario = @MOROLSESION, Estado_Usuario = @MOESTADOSESION
WHERE @MOUSUARIOSESION = Usuario_Usuario

CREATE PROCEDURE MODIFICAR_CARGO
@MOCODIGOCARGO varchar(10),
@MONOMBRECARGO varchar(15),
@MOESTADOCARGO varchar(10)
AS
UPDATE CARGO
SET Nombre_Cargo = @MONOMBRECARGO,Estado_Cargo = @MOESTADOCARGO
WHERE @MOCODIGOCARGO = Codigo_Cargo

CREATE PROCEDURE MODIFICAR_COMPROBANTE
@MORAZON_COMPROBANTE varchar(70),
@MOFECHA_COMPROBANTE datetime, 
@MONOMBRE_COMPROBANTE varchar(40),
@MOESTADO_COMPROBANTE varchar(10)
AS
UPDATE COMPROBANTE
SET Fecha_Comprobante = @MOFECHA_COMPROBANTE ,Nombre_Comprobante = @MONOMBRE_COMPROBANTE, Estado_Comprobante = @MOESTADO_COMPROBANTE
WHERE @MORAZON_COMPROBANTE = Razon_Comprobante

CREATE PROCEDURE MODIFICAR_FORMAS_PAGOS
@MOCODIGO_FORMAPG varchar(10),
@MONOMBRE_FORMAPG varchar(20),
@MOESTADO_FORMAPG varchar(10)
AS
UPDATE FORMAS_PAGOS
SET Codigo_FormaPG = @MOCODIGO_FORMAPG ,Nombre_FormaPG = @MONOMBRE_FORMAPG,Estado_FormaPG = @MOESTADO_FORMAPG
WHERE @MOCODIGO_FORMAPG = Codigo_FormaPG

CREATE PROCEDURE MODIFICAR_PROVEEDORES
@MOCODIGO_PROVEEDORES numeric,
@MODIRECCION_PROVEEDORES varchar(45),
@MOTELEFONO_PROVEEDORES numeric,
@MONOMBRE_PROVEEDORES varchar(35),
@MORAZON_COMPROBANTE_PROVEEDORES_FK  varchar(70),
@MOESTADO_PROVEEDORES varchar(10)
AS
UPDATE PROVEEDORES
SET Direccion_Proveedores = @MODIRECCION_PROVEEDORES,Telefono_Proveedores = @MOTELEFONO_PROVEEDORES,Nombre_Proveedores = @MONOMBRE_PROVEEDORES,Razon_Comprobante_Proveedores_FK = @MORAZON_COMPROBANTE_PROVEEDORES_FK,Estado_Proveedores = @MOESTADO_PROVEEDORES
WHERE @MOCODIGO_PROVEEDORES = Codigo_Proveedores 

CREATE PROCEDURE MODIFICAR_EMPLEADO
@MOCODIGO_EMPLEADO numeric,
@MOID_EMPLEADO numeric,
@MONOMBRE_EMPLEADO varchar(30),
@MODIRECCION_EMPLEADO varchar(25),
@MOTELEFONO_EMPLEADO Numeric,
@MOFECHANACI_EMPLEADO datetime,
@MOUSUARIO_INISESION_EMPLEADO_FK varchar(50),
@MOSALARIO_EMPLEADO float,
@MOGENERO_EMPLEADO varchar(10),
@MOCODIGO_CARGO_EMPLEADO_FK varchar(10),
@MOESTADO_EMPLEADO varchar(10),
@MOCODIGO_PROVEEDORES_EMPLEADO_FK numeric
AS
UPDATE EMPLEADO
SET Id_Empleado = @MOID_EMPLEADO,Nombre_Empleado = @MONOMBRE_EMPLEADO,Direccion_Empleado = @MODIRECCION_EMPLEADO,Telefono_Empleado  = @MOTELEFONO_EMPLEADO,FechaNaci_Empleado = @MOFECHANACI_EMPLEADO,Genero_Empleado = @MOGENERO_EMPLEADO,Salario_Empleado = @MOSALARIO_EMPLEADO,Usuario_Usuario_Empleado_FK = @MOUSUARIO_INISESION_EMPLEADO_FK,Codigo_Cargo_Empleado_FK = @MOCODIGO_CARGO_EMPLEADO_FK,Estado_Empleado = @MOESTADO_EMPLEADO,Codigo_Proveedores_Empleado_FK = @MOCODIGO_PROVEEDORES_EMPLEADO_FK
WHERE @MOCODIGO_EMPLEADO = Codigo_Empleado

CREATE PROCEDURE MODIFICAR_FACTURA_COMPRA
@MOCODIGO_FACTCOMP numeric,
@MOCODIGO_EMPLEADO_FACTCOMP_FK numeric,
@MOCODIGO_PROVEEDORES_FACTCOMP_FK numeric,
@MOFECHA_FACTCOMP datetime,
@MOVALOR_FACTCOMP Float,
@MOESTADO_FACTCOMP varchar(10)
AS
UPDATE FACTURA_COMPRA
SET Codigo_Empleado_FactComp_FK = @MOCODIGO_EMPLEADO_FACTCOMP_FK,Codigo_Proveedores_FactComp_FK = @MOCODIGO_PROVEEDORES_FACTCOMP_FK,Fecha_FactComp = @MOFECHA_FACTCOMP,Valor_FactComp = @MOVALOR_FACTCOMP,Estado_FactComp = @MOESTADO_FACTCOMP
WHERE @MOCODIGO_FACTCOMP = Codigo_FactComp

CREATE PROCEDURE MODIFICAR_CLIENTE
@MOCODIGO_CLIENTE numeric,
@MOID_CLIENTE numeric,
@MONOMBRE_CLIENTE varchar(30),
@MODIRECCION_CLIENTE varchar(25),
@MOTELEFONO_CLIENTE Numeric,
@MOGENERO_CLIENTE varchar(10),
@MOCODIGO_EMPLEADO_CLIENTE_FK numeric,
@MOESTADO_CLIENTE varchar(10)
AS
UPDATE CLIENTE
SET Id_Cliente = @MOID_CLIENTE,Nombre_Cliente = @MONOMBRE_CLIENTE,Direccion_Cliente = @MODIRECCION_CLIENTE,Telefono_Cliente  = @MOTELEFONO_CLIENTE,Genero_Cliente = @MOGENERO_CLIENTE,Codigo_Empleado_Cliente_FK = @MOCODIGO_EMPLEADO_CLIENTE_FK,Estado_Cliente = @MOESTADO_CLIENTE
WHERE @MOCODIGO_CLIENTE = Codigo_Cliente

Create procedure MODIFICAR_FACTURA_VENTA
@MOCODIGO_FACTVENT numeric,
@MOCODIGO_EMPLEADO_FACTVENT_FK numeric,
@MOCODIGO_CLIENTE_FACTVENT_FK numeric,
@MOFECHA_FACTVENT datetime,
@MOVALOR_FACTVENT float,
@MOESTADO_FACTVENT varchar(10)
AS
UPDATE FACTURA_VENTA
SET Codigo_Empleado_FactVent_FK = @MOCODIGO_EMPLEADO_FACTVENT_FK,Codigo_Cliente_FactVent_FK = @MOCODIGO_CLIENTE_FACTVENT_FK,Fecha_FactVent = @MOFECHA_FACTVENT,Valor_FactVent = @MOVALOR_FACTVENT ,Estado_FactVent = @MOESTADO_FACTVENT
WHERE @MOCODIGO_FACTVENT = Codigo_FactVent

CREATE PROCEDURE MODIFICAR_RECIBO_CAJA
@MOCODIGO_RECICAJA numeric,
@MOCODIGO_CLIENTE_RECICAJA_FK numeric,
@MOCODIGO_FACTVENT_RECICAJA_FK numeric,
@MOFECHA_RECICAJA datetime,
@MOVALOR_RECICAJA FLOAT,
@MODESCRIPCION_RECICAJA VARCHAR(50),
@MOESTADO_RECICAJA VARCHAR(10)
AS
UPDATE RECIBO_CAJA
SET Codigo_Cliente_ReciCaja_FK = @MOCODIGO_CLIENTE_RECICAJA_FK,Codigo_FactVent_ReciCaja_FK = @MOCODIGO_FACTVENT_RECICAJA_FK,Fecha_ReciCaja = @MOFECHA_RECICAJA,Valor_ReciCaja = @MOVALOR_RECICAJA,Descripcion_ReciCaja = @MODESCRIPCION_RECICAJA,Estado_ReciCaja = @MOESTADO_RECICAJA
WHERE @MOCODIGO_RECICAJA = Codigo_ReciCaja 

CREATE PROCEDURE MODIFICAR_PAGOS
@MONUMERO_PAGOS INT,
@MOVALOR_PAGOS FLOAT,
@MOCODIGO_FORMAPG_PAGOS_FK VARCHAR(10),
@MOFECHA_PAGOS datetime,
@MOCODIGO_EMPLEADO_PAGOS_FK NUMERIC,
@MOCODIGO_CLIENTE_PAGOS_FK NUMERIC,
@MOCODIGO_FACTVENT_PAGOS_FK NUMERIC,
@MOCODIGO_FACTCOMP_PAGOS_FK NUMERIC,
@MOESTADO_PAGOS VARCHAR(10)
AS
UPDATE PAGOS
SET Valor_Pagos = @MOVALOR_PAGOS,Codigo_FormaPG_Pagos_FK = @MOCODIGO_FORMAPG_PAGOS_FK,Fecha_Pagos = @MOFECHA_PAGOS,Codigo_Empleado_Pagos_FK = @MOCODIGO_EMPLEADO_PAGOS_FK,Codigo_Cliente_Pagos_FK = @MOCODIGO_CLIENTE_PAGOS_FK,Codigo_FactVent_Pagos_FK = @MOCODIGO_FACTVENT_PAGOS_FK,Codigo_FactComp_Pagos_FK = @MOCODIGO_FACTCOMP_PAGOS_FK, Estado_Pagos = @MOESTADO_PAGOS
WHERE @MONUMERO_PAGOS = Numero_Pagos